Locked orientation
elvenstudios/Colorie pull request #5
Opened 2019-07-22 23:33 UTC by jdial1

2019-07-23 23:40 UTC, 10ndavis requested changes

2019-07-23 23:40 UTC, 10ndavis commented on lib/main.dart
> +
let's clean this up a bit by making it an arrow function
something like this:
` SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp],
  ).then(
    (_) => runApp(MyApp()),
  );`

The commas help dart format the code correctly. right click then press "format with dartfmt"

2019-07-24 13:40 UTC, jdial1 commented on lib/main.dart
> +
Corrected

2019-07-24 14:53 UTC, 10ndavis approved these changes

2019-07-24 14:53 UTC, merged